### ISSUE TITLE
Add Activity Selection Algorithm

### ISSUE THREAD

**Issue by ai7zbym87snhk** [ai7zbym87snhk/DSA#8]
Write an algorithm using the greedy approach to measure the total activities a person can do at a single time. Remember there should not be an overlap of time and endtime is not sorted

**Comment by shyam1112** [comment]
@ai7zbym87snhk Hello, Can you please assign this task to me !

**Comment by ai7zbym87snhk** [comment]
@shyam1112 make a PR directly and mention it here

**Comment by Kaushik2201** [comment]
Added Activity Selection Algorithm in java and made a PR #9 Kindly merge it.
